# File:         labels.yml
# Description:  Defines labels to be used on GitHub
---
# Autorelease
- name: "autorelease: pending"
  color: "757575"
  description: ""
- name: "autorelease: tagged"
  color: "616161"
  description: ""
- name: "autorelease: snapshot"
  color: "424242"
  description: ""
- name: "autorelease: published"
  color: "212121"
  description: ""

# Priority
- name: "priority: needs triage"
  color: "00bfa5"
  description: ""
- name: "priority: none"
  color: "00c853"
  description: ""
- name: "priority: very low"
  color: "64dd17"
  description: ""
- name: "priority: low"
  color: "aeea00"
  description: ""
- name: "priority: medium"
  color: "ffd600"
  description: ""
- name: "priority: high"
  color: "ff6d00"
  description: ""
- name: "priority: critical"
  color: "d50000"
  description: ""

# Status
- name: "status: review pending"
  color: "607d8b"
  description: ""
- name: "status: approved"
  color: "78909c"
  description: ""
- name: "status: duplicate"
  color: "90a4ae"
  description: ""
- name: "status: cancelled"
  color: "b0bec5"
  description: ""
- name: "status: won't do"
  color: "cfd8dc"
  description: ""

# Type
- name: "type: bug"
  color: "b71c1c"
  description: ""
- name: "type: feature"
  color: "0d47a1"
  description: ""
- name: "type: documentation"
  color: "01579b"
  description: ""
- name: "type: enhancement"
  color: "006064"
  description: ""
- name: "type: refactor"
  color: "4a148c"
  description: ""
- name: "type: test"
  color: "ffee58"
  description: ""
- name: "type: design"
  color: "03a9f4"
  description: ""
- name: "type: plan"
  color: "009688"
  description: ""
