# File:         report_bug.yml
# Description:  GitHub Template For Bug Reports
---
name: 🐛 Bug Report
description: "File a Bug Report"
title: "[Bug] <title>"
labels: ["type: bug", "status: review pending", "priority: needs triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out a bug report!

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Please provide a clear and concise description of the bug you are experiencing.
    validations:
      required: true

  - type: textarea
    id: current_behavior
    attributes:
      label: Current Behavior
      description: What is the current behavior that you are currently experiencing?
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What behavior did you expect to see?
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Please provide clear and concise instructions on how to replicate the bug.
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide detailed information about your environment, including the project version.
      placeholder: |
        Version:
    validations:
      required: false

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information / Files
      description: |
        Is there any additional information that you think would be helpful to investigate this bug?
        Please attach any screenshots or log files that might help as well.
        Tip: You can attach images or other files by clicking this area to highlight it and then
        dragging files in.
    validations:
      required: false

  - type: checkboxes
    id: pull_request_offer
    attributes:
      label: Pull Request
      description: If confirmed, would you be willing to submit a Pull Request for this bug?
      options:
        - label: Yes, I would like to submit a Pull Request for this bug, if confirmed.
          required: false

  - type: checkboxes
    id: code_of_conduct
    attributes:
      label: Code of Conduct
      description: |
        By submitting this issue, you agree to follow our
        [Code of Conduct](https://github.com/github_username/repo_name/blob/main/docs/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow project_name's Code of Conduct.
          required: true
