# File:         request_feature.yml
# Description:  GitHub Template For Feature Requests
---
name: 🚀 Feature Request
description: "Request a new feature"
title: "[Feature] <title>"
labels: ["type: feature", "status: review pending", "priority: needs triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out a feature request!

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: |
        Please provide a clear and concise explanation of what you want to happen.
        Describe the problem this solves as well as any considered challenges or drawbacks.
    validations:
      required: true

  - type: textarea
    id: changes
    attributes:
      label: Alternative Solutions
      description: |
        Have you considered any other solutions? If so, describe them here. Also describe any
        workarounds that are currently in-use in place of the proposed feature.
    validations:
      required: false

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information / Files
      description: |
        Is there any additional information that you think would be helpful?
        Please attach any screenshots or log files that might help as well.
        Tip: You can attach images or other files by clicking this area to highlight it and then
        dragging files in.
    validations:
      required: false

  - type: checkboxes
    id: pull_request_offer
    attributes:
      label: Pull Request
      description: |
        If confirmed, would you be willing to submit a Pull Request for this feature?
      options:
        - label: Yes, I would like to submit a Pull Request for this feature, if approved.
          required: false

  - type: checkboxes
    id: code_of_conduct
    attributes:
      label: Code of Conduct
      description: |
        By submitting this issue, you agree to follow our
        [Code of Conduct](https://github.com/github_username/repo_name/blob/main/docs/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow project_name's Code of Conduct.
          required: true
