# File:         request_documentation.yml
# Description:  GitHub Template For Documentation Requests
---
name: 📖 Documentation Request
description: "Request an update to the documentation"
title: "[Documentation] <title>"
labels:
  ["type: documentation", "status: review pending", "priority: needs triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out a documentation request!

  - type: textarea
    id: description
    attributes:
      label: Current Documentation
      description: Please provide a clear and concise description of the current documentation.
    validations:
      required: true

  - type: textarea
    id: changes
    attributes:
      label: Proposed Changes
      description: Please provide a clear description of the changes that you would like to see.
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information / Files
      description: |
        Is there any additional information that you think would be helpful for documentation?
        Please attach any screenshots or log files that might help as well.
        Tip: You can attach images or other files by clicking this area to highlight it and then
        dragging files in.
    validations:
      required: false

  - type: checkboxes
    id: pull_request_offer
    attributes:
      label: Pull Request
      description: |
        If confirmed, would you be willing to submit a Pull Request for this documentation?
      options:
        - label: Yes, I would like to submit a Pull Request for this documentation, if approved.
          required: false

  - type: checkboxes
    id: code_of_conduct
    attributes:
      label: Code of Conduct
      description: |
        By submitting this issue, you agree to follow our
        [Code of Conduct](https://github.com/github_username/repo_name/blob/main/docs/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow project_name's Code of Conduct.
          required: true
