# File:         continuous_integration.yml
# Description:  GitHub Action to run continuous integration tasks
#               Makes use of GitHub Super Linter and pytest
#               Link: https://github.com/marketplace/actions/super-linter
---
name: 🔬 Continuous Integration

on:
  push:
    branches-ignore:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_call:

jobs:
  super-linter:
    name: 🔎 Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: 💾 Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 🔎 Run GitHub Super Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYTHON_BLACK_CONFIG_FILE: pyproject.toml
          PYTHON_ISORT_CONFIG_FILE: pyproject.toml
          VALIDATE_PYTHON_MYPY: false

  pytest:
    name: 🧪 Run pytest
    runs-on: ubuntu-latest
    steps:
      - name: 💾 Checkout Repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: 🔌 Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: 🧪 Run pytest
        run: |
          pytest
