# File:         continuous_deployment.yml
# Description:  GitHub Action to run continuous deployment tasks
#               Makes use of Google's "Release Please" GitHub Action
#               Link: https://github.com/marketplace/actions/release-please-action
---
name: 📦 Continuous Deployment

on:
  push:
    branches:
      - main
      - master

jobs:
  continuous-integration:
    name: 🔬 Continuous Integration
    uses: ./.github/workflows/continuous_integration.yml

  release-please:
    name: 📦 Update Release Pull Request
    runs-on: ubuntu-latest
    needs: continuous-integration
    steps:
      - name: Release Please
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: python
          changelog-path: docs/changelog.md
          token: ${{ secrets.RELEASE_SECRET }}
